### ISSUE TITLE
Cannot read config file properly 

### ISSUE THREAD

**Issue by Kazom** [rudders/homebridge-wemo#1]
Error: Parse error on line 14:
... "WeMo",			"name": 'Test',			"descript
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by rudders** [comment]
can you post your config.son please - but try " not ' around "Test" - and is your Wemo's name inn the Wemo App really Test?

**Comment by Kazom** [comment]
Hey sorry ended up fixing this by changing the name of my wemo to the default one in the config file. Thanks!

**Comment by rudders** [comment]
Okay - so long as you got it to work. New version of homebridge-platform-wemo should be up soon - give it a try also.
