### ISSUE TITLE
WeMo Switch 13A Model F7C027uk

### ISSUE THREAD

**Issue by wim1732** [rudders/homebridge-wemo#103]
Is this supported? I’ve successfully used my led bulbs with link but this device is not recognised. Regards Graham

**Comment by bwp91** [comment]
Hi Graham,
Yes this device should be supported.
Have you gotten it working at all?

**Comment by wim1732** [comment]
Hi Ben,
I can see it under plugins/homebridge-wemo/my devices but it doesn't appear under Homebridge Accessories or in the Apple Home App. To make my Wemo Link work with the led bulbs I had to add it's serial number to Settings, do I need to add the switch serial number somewhere?

**Comment by wim1732** [comment]
Correction, I can't see it under devices, it's the Wemo Link but the icon is showing a switch!

**Comment by wim1732** [comment]
I've added it to Wemo Outlets with a manual IP and it's working now!

**Comment by bwp91** [comment]
glad you got this sorted! out of interest, why did you mention the wemo link in this issue? i thought the wemo link was just used to support light bulbs

**Comment by wim1732** [comment]
I mentioned the WemoLink because what was confusing me was that under my devices I could see the picture of a switch (see enclosed) but when I looked carefully the details were the WemoLink. The switch does appear in my devices correctly with the correct picture.
