### ISSUE TITLE
Terminal stopped being able to find WeMos

### ISSUE THREAD

**Issue by jtepp** [rudders/homebridge-wemo#2]
my WeMo switches are successfully connected to my ipod touch with the app. On my mac, the terminal goes on forever saying this:

[Monitor] Error finding device 'M': WeMoSearchTimeoutError
[Monitor] Continuing search for WeMo device with exact name 'M'...

I have tried changing the name in the app and the config.json but it won't work. Please, somebody help!

**Comment by rudders** [comment]
please post you config.json - suspect a problem there.

**Comment by jtepp** [comment]
It was the exact one that you posted as a sample just with my wemo's names (I have 2). I cleared out my config.json. And every time home bridge stopped working, I stopped terminal, redrawn loaded a config.json from idownloadblog and pasted in my details as if it would make a difference... But since everyone is asking me what to get me for my birthday in like 3 weeks, I'll just get authentic HomeKit outlets. Would be nice to get the wemo's working too. Except they would disconnect themselves from the wemo's app too because they're the old switches. Not sure if you have any chance at fixing. Would you still like my config.json?

**Comment by rudders** [comment]
Sure - and a bit more of the log perhaps. Happy to help get it going - have you tried my other plugin - homebridge-platform-wemo? Works with Bulbs and Switches currently - new version due in the next day or so.

**Comment by jtepp** [comment]
I'll try post my config tomorrow as I'm going to bed now. Thanks for the help. I installed your wemo's platform and timon's wemo's client but couldn't get it working either. X and Y didn't work so I set devices to 1 (wasn't sure if that was the amount or name of wemo's so I set wemo's name to "1" also on its app) and I set the timeout time to 100 seconds but it never ended and nothing happened. I hope your upcoming version will do the trick. I miss being able to tell Siri to turn my computer on...

**Comment by rudders** [comment]
`expected_accessories` is the total count of Wemo bulbs and Switches you have - it is optional and if not specified the timeout value will be used to wait for the discovery process to conclude. 

`timeout` is specified in seconds and will default to 10 seconds.

```javascript
"platforms": [
        {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "expected_accessories" : "x",
          "timeout" : "y"
        }   
    ]

```

**Comment by jtepp** [comment]
Yeah I tried using that but it still wouldn't find my wemo's, gave me a similar error message to before, must be the wemo's.

**Comment by rudders** [comment]
Possibly some network issues if it never sees the wemo's at all what platform are you on?

try a long timeout.

```"platforms": [
        {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "timeout" : "20"
        }   
    ]```

**Comment by jtepp** [comment]
Ohhhh. I think I know the problem. It's with the wemo's app itself. In my house, I have three wifi networks. Two from my carrier (2.5&5ghz) and one from time capsule. The only one that actually works is the 5ghz one but the wemo app is stuck on the 2.5 GHz one. Don't think there's any way to change that...

**Comment by rudders** [comment]
Wemo's only talk on 2.5Ghz from memory - but there's your problem right there! Good luck.

**Comment by jtepp** [comment]
Yup. Thanks. My brother just came home from university and I'll have him redo our wifi. Thanks, happy holidays ;)
