### ISSUE TITLE
Can't Make Outlet Show As Air Purifier

### ISSUE THREAD

**Issue by holyshityouguys** [rudders/homebridge-wemo#23]
### What issue do you have? Please be as thorough and explicit as possible.

I am using the "outlet" options section as with the old version and trying to turn my outlets into air purifiers. The log shows the "ShowAs" is still "outlet" even though the options say Air Purifier.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?

3.4.1. I just moved over from the old plugin, which worked fine.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

Wemo outlet, v1 and v2

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi, 

Can you post your config?

There are no code changes between the latest version of homebridge-platform-wemo and homebridge-wemo except the name changes.

**Comment by holyshityouguys** [comment]
{
    "name": "Wemo",
    "mode": "auto",
    "wemoOutlets": [
        {
            "label": "Master Bedroom Air Purifier",
            "serialNumber": "221327K010113D",
            "showAs": "purifier",
            "manualIP": "192.168.0.91"
        }
    ],
    "platform": "Wemo"
}

Dan Rodriguez m. <removed>

**Comment by bwp91** [comment]
Can you update to the beta version I have just pushed, 3.4.2-beta.0, to see if this fixes this?

Thanks

**Comment by holyshityouguys** [comment]
Yes it fixed it

Dan Rodriguez m. <removed>
