### ISSUE TITLE
Ignored Devices function is gone

### ISSUE THREAD

**Issue by WayneKP** [rudders/homebridge-wemo#24]
I used to use the Ignored devices function but now it is gone so is there another way to disable devices as I found this feature was useful to me but I can't speak for other users

* **Is your feature request related to a problem? Please describe.**

* **Any particular Wemo devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Yes, this change was mentioned in the changelog.

'Hide From HomeKit' is inside the different device type sections, for example

<img width="749" alt="Screenshot 2021-08-01 at 09 05 40" src="https://user-images.githubusercontent.com/43026681/127764050-bd4d8562-9760-441b-81f6-3d0da76a32f8.png">

Designed to make it easier to know which serial number relates to which device if you have a lot of ignored devices

**Comment by WayneKP** [comment]
Hello and thank you, it would probably help me if I had read the changelog :) :)  I appreciate what a brilliant job you have done for everybody who uses Homebridge and Wemo , I started to have a go at making my own plugin and found it is an unbelievable amount of work so I know you have put in a huge effort so thank you and for continuing to provide support to the community Thanks Wayne
