### ISSUE TITLE
Existing Wemo Plugs on Reboot of Homebridge Error

### ISSUE THREAD

**Issue by thk-socal** [rudders/homebridge-wemo#25]
### What issue do you have? Please be as thorough and explicit as possible.
I have existing plugs, if those plugs are offline and Homebridge is restarted, the plugin attempts to reconnect (which is awesome), but when the plugs are brought back online, the plugin does not find them until the bridge is restarted.
This DOES NOT happen if I unplug and replug the unit in while Homebridge is running. 

It appears that perhaps the IP address is not known for the system to attempt reconnect if the device is offline when Homebridge is first booted up. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 4
Node.js = 14.17.4
NPM = 6.14.14

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?
Version is 4.0.0 and appears to be an issue with the NEW plugin I do not remember seeing this with the old plugin.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wemo Mini : Model F7C063 (4 of them, and they all fail)

### Please paste any relevant logs below.
Errors are "[device name] awaiting (re)connection and will retry in 30s."

**Comment by bwp91** [comment]
Hi @cscott365 

I’ve gotten my own wemo outlet out the drawer after weeks of not needing it, to try and recreate this issue.

It’s always worked well for me, auto discovery, reconnecting if it went offline. But this time I am having a terrible time with it. I don’t know if it’s the firmware update, my router (eero) software update, but I can hardly get it to work at all… even with a manual IP address - it’s definitely connected to the wifi (i can see in eero app) but not working even with the wemo app.

So I can’t really debug myself.

There were no changes to the code between latest of version 3 and version 4, except for plugin name references. So this shouldn’t be an issue.

> It appears that perhaps the IP address is not known for the system to attempt reconnect if the device is offline when Homebridge is first booted up.

The plugin sends out a broadcast request across the network and wemo devices respond with with IP address and other data. This is how the plugin gets IPs in the first place, for new devices and for existing devices if they change IP.

Devices show this dreaded `awaiting (re)connection` message when (auto-discovery) devices don’t respond to this broadcast and when manual IP devices don’t respond at the configured IP.

Something you can do is to get the “broadcaster” to debug to the homebridge log, you can do this by adding to the wemo config 

```
"debugNodeSSDP": true,
```

and restart the plugin. It will output a lot to the log and it will repeat every 30 seconds or so.

When a wemo device is working properly you will be able to see the device in the list of devices that respond to the broadcast request (look for belkin in the data)

It would be interesting if you were to unplug your outlet, then plug it back in (to recreate the issue) wait a few moments for it to setup again and check the logs to see if the device reappears in the list. 

If it doesn’t, this is the reason why it isn’t being initialised in homebridge again.

If it does, then there is obviously something wrong in the code which I would look into!

Thanks

**Comment by bwp91** [comment]
I’ll add that the “broadcaster” runs exactly the same on the first run when the plugin starts, as it does on each discovery run.

I mean that there is nothing special about the first run, so theoretically a homebridge restart shouldn’t be needed to get a device working again

**Comment by bwp91** [comment]
Can you update to the new beta?

I've spent a while rewriting a substantial amount of the plugin, hopefully for the better!

There may still be some issues but it's working for me well.

**Comment by thk-socal** [comment]
Need to wait until this weekend for that. In the middle of other home installation work. Will check this weekend for you though.

**Comment by thk-socal** [comment]
Actually had a few and dropped beta 10 in now. Appears to be good now for my issue and I will re-open if it returns.
