### ISSUE TITLE
wemo plugin can't update or remove  

### ISSUE THREAD

**Issue by wallacepost** [rudders/homebridge-wemo#26]
Hi,
the plugin sudden can't remove or update. 

screen shot : https://www.dropbox.com/s/drs7m9ksmngiv3v/Screen%20Shot%202021-08-03%20at%2011.36.12%20pm.png?dl=0

Details of your setup.

Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
HOOBS

Which version of Homebridge/HOOBS do you have?
3.3.3

Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
hoobs hub

Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?
Version is 3.1.0 , it happened last update

Which Wemo devices do you have that are causing issues?
all wemo plugs are still working, but just can't update this wemo plugin anymore. i try to remove this manually, the hoobs then will not restart.

**Comment by bwp91** [comment]
Hi,

Can you still edit the configuration for this plugin in the hoobs ui?

**Comment by wallacepost** [comment]
> Hi,
> 
> Can you still edit the configuration for this plugin in the hoobs ui?

sorry for late reply, yes it can still edit under hoobs configuration UI.


![Screen Shot 2021-08-13 at 10 39 11 pm](https://user-images.githubusercontent.com/65918663/129358412-bbec62b9-b6ed-4936-9714-f4a0cf0112de.png)

**Comment by bwp91** [comment]
Set the 'Disable Plugin' to true and restart HOOBS. This will remove the existing accessories before uninstalling so they don't then become duplicated with the next plugin.

After HOOBS has restarted, just check they have been removed. Then STOP the hoobs service, and from the hoobs terminal run these two commands:

```
cd ~/.hoobs/
```

```
npm uninstall homebridge-platform-wemo
```

Then restart hoobs and you should find the plugin has disappeared. You can then install `homebridge-wemo` plugin and it will find and re-add your accessories as new.

**Comment by wallacepost** [comment]
> npm uninstall homebridge-platform-wemo

thank you very much mate, it works now. I followed your instruction + remove the old wemo setting in  CONFIGURATION --> ADVANCE , otherwise the hoob will not start. 

19/08/2021, 12:47:34 am Error: No plugin was found for the platform "BelkinWeMo" in your config.json. Please make sure the corresponding plugin is installed correctly.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/src/pluginManager.ts:249:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:335:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:321:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:153:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
19/08/2021, 12:47:34 am Got SIGTERM, shutting down Bridge...

**Comment by bwp91** [comment]
Forgot this step! Sorry... but glad you figured it out and all (hopefully) working again!
