### ISSUE TITLE
No more power consumption bars in the Eve app

### ISSUE THREAD

**Issue by permaMonk** [rudders/homebridge-wemo#28]
Hi.

Yesterday I switched to to the new home base "homebridge-wemo". I processed the shift from "homebridge-platform-wemo" exactly according to the instructions in your [readme](https://github.com/bwp91/homebridge-platform-wemo/blob/latest/README.md). And everything worked fine. No problems. I thought.

My "homebridge-wemo" config:
{
    "name": "Belkin WeMo",
    "mode": "auto",
    "wemoInsights": [
        {
            "label": "Waschmaschine",
            "serialNumber": "xxx",
            "wattDiff": 2,
            "timeDiff": 30
        }
    ],
    "platform": "Wemo"
}

I only add the "label"-line to the new config.

Problem:
Since then I see no more power consumption bars in the Eve app. The line hangs at 0 watts.
![Eve_App](https://user-images.githubusercontent.com/60167885/128915626-198f188f-ea29-455b-b3fd-cd258194370f.PNG)

But the washing machine is definitely in use.
![Wemo_App](https://user-images.githubusercontent.com/60167885/128915981-a36e7d8c-59c1-4646-ab89-4f8a932be75c.PNG)

What I´ve done:
- today updated to homebridge-wemo v4.1.0
- take the Wemo Insight Switch out the power outlet, wait 20 sec. and plug it in again

Any ideas what I could do?

**Comment by bwp91** [comment]
The logs are helpful in seeing what’s wrong.
Can you put the plugin in debug mode, restart the plugin and check the plugin connects to the device? 

The plugin relies on data received from the device, if the device isn’t connected to the plugin then no data will be received hence the characteristics like wattage not updating

**Comment by bwp91** [comment]
Between the last version of platform-wemo and the new version of wemo, nothing has changed with regards to how the plugin deals with data received and updating the homekit data, so it does sound more like a connection issue between the device and the plugin, perhaps the plugin isn’t getting the data updates from the device.
The logs will help with diagnosing the issue

**Comment by permaMonk** [comment]
Ok it comes.
[Wemo_Log_01.txt](https://github.com/bwp91/homebridge-wemo/files/6964031/Wemo_Log_01.txt)

**Comment by bwp91** [comment]
has there been any recent firmware update for this device?

**Comment by permaMonk** [comment]
I don’t know. This drives automatically. I think I will get a notification if there has been a firmware update. But I can say there have been no notification about this in the last weeks.

Firmware Version is WeMo_WW_2.00.11532.PVT-OWRT-Insight. Hardware Version is v1.

—

**Comment by bwp91** [comment]
In the logs you sent, the device is reporting to be in standby mode with a very low power usage. For example, 

```
<InsightParams>8|1628605133|32|6353|57209|1209600|432|55|49136626|295672028|4000</InsightParams>
```

The first number here, `8`, tells the plugin the device is in standby (on, but insignificant power usage). This number shows as `0` if the device is off, or `1` if the device is on with significant power usage.

The eighth number, `55` in this case, is the current wattage multiplied by 1000. So the plugin divides this by 1000 in this case the wattage is 0.055W.

This is the case throughout the whole section of logs you sent.

Would you be able to get me some logs from when the device is ON and drawing some significant power, like when the washing machine is mid-cycle.

Also a screenshot from the wemo app with the energy usage at one point during this log section so I can compare what I can see in the screenshot with one line in the logs.

**Comment by permaMonk** [comment]
Ok I've made a washing. But before posting the log file and pictures I've to tell you I restarted the Apple TV box. And that's maybe the solution.

Logfile with power consumption:
[Wemo_Log_02.txt](https://github.com/bwp91/homebridge-wemo/files/6969265/Wemo_Log_02.txt)

Wemo App:
![Wemo_2](https://user-images.githubusercontent.com/60167885/129050470-940003c6-e05a-4969-a4f4-734f41eebb34.jpg)

Eve App:
![Eve_2](https://user-images.githubusercontent.com/60167885/129050499-0813015e-a3e1-41d0-addb-bd9af7733296.jpg)

And voila here I see again a little bar.

Any idea what happened?

**Comment by bwp91** [comment]
It looks like it's working properly again? I honestly have no idea what an appletv restart could have fixed... but at least it did!

I'll keep this issue open for a few days, let me know in a few days if it's been working well, or indeed sooner if you're having issues again.

**Comment by permaMonk** [comment]
Yes I will do that.

But, maybe, it’s a good idea to tell the users in your change repository readme it could help to restart their Homekit hub.

—

**Comment by permaMonk** [comment]
Unfortunately, the strange behavior occurred again today. The washing machine is running and therefore consumes electricity, this is also displayed in the Wemo app but not in the Eve app. Nothing at all - zero line. Screenshots available.

Unfortunately unplugging the Wemo Insight plug did not help. I can't restart Apple TV until tomorrow and then report whether it helps.

1 day later:
After restart the ATV the Eve app shows bars again. Strange behavior. Have no explanation

**Comment by PlatGitHub468** [comment]
Hello, 
I have Wemo Insight Switch.  How do you show the power graph in Eve App?  It's not obvious for me how to do that.

**Comment by permaMonk** [comment]
Not sure if I should answer. Not sure if you are kidding. 

You understand the concept of Homebridge and their plugins?

This plugin here “translate” the interactions of a Wemo device via Homebridge (running on a hardware e.g. a RasPi) to HomeKit. Therefore it can be represented by the Eve app.

**Comment by bwp91** [comment]
> Hello,
> I have Wemo Insight Switch. How do you show the power graph in Eve App? It's not obvious for me how to do that.

Sometimes the graph can be hidden. On the accessory page click on Edit at the top and make sure “Total Consumption” is shown. The graph is shown here.

**Comment by PlatGitHub468** [comment]
thanks.  I think I got it working now

**Comment by bwp91** [comment]
> thanks. I think I got it working now

Just don’t absolutely rely on it 🤣 as @permaMonk would know.

The fact it is working *most* of the time but not sometimes makes me think it’s more like an intermittent connection issue.

The plugin relies on real-time and constant notifications from the insight to calculate the values and the graph, i mean, if there is a connection problem and the plugin doesn’t receive these values for a while, it won’t be able to request the values it has missed per se.

@permaMonk i don’t suppose you still have logs from this day that it didn’t work?

Ideally debug logs, but i understand that having the plugin in debug mode for days and days anticipating a day that it doesn’t work properly isn’t really feasible

**Comment by permaMonk** [comment]
Sorry no logs. Problem is I’m not always near the HK / HB Installation when this happens. But next time I’ll fist log this bevor I try to solve it - promise.

Next I’ll try is a new ATV. Maybe this will make it.

—

Several hours later
It starts again. Watching machine takes 1600W, Wemo show this and the Eve app bars = nothing. I’ll start a debug log later.

**Comment by permaMonk** [comment]
Washing machine is running. Wemo app show consumption is more than 4W. Eve app also presents correct values.

So here is the log. Just to verify again.

[Homebridge Wemo plugin Log 02.txt](https://github.com/bwp91/homebridge-wemo/files/7021409/Homebridge.Wemo.plugin.Log.02.txt)
