### ISSUE TITLE
Ignored Devices

### ISSUE THREAD

**Issue by Danimal1024** [rudders/homebridge-wemo#32]
In the new version I don't see a way to ignore devices. In the previous version I ignored all newer Wemos that are HK compatible out of the box. I would like to do that again but don't see how to do it. Thanks.

**Comment by bwp91** [comment]
Hi @Danimal1024 

Devices can be hidden from Homebridge using the 'Ignore From HomeKit' option in each device type section in the config:

<img width="497" alt="Screenshot 2021-08-25 at 08 32 54" src="https://user-images.githubusercontent.com/43026681/130746785-49f3e69a-d783-4557-aa14-82a02e11783c.png">

**Comment by Danimal1024** [comment]
Thanks! So sorry I missed that. I kept looking in those drop-downs and didn't read through it enough I guess.
