### ISSUE TITLE
Remove HomeKit Native Accessory

### ISSUE THREAD

**Issue by vicc** [rudders/homebridge-wemo#33]
### What issue do you have? Please be as thorough and explicit as possible.
I connected my Wemo Outlet to HomeKit and set it as a purifier type and it works. The problem is that both the outlet and purifier are visible on HomeKit.

Config File:
```
{
    "name": "Wemo",
    "mode": "auto",
    "wemoOutlets": [
        {
            "label": "Wemo Air Purifier",
            "serialNumber": "M1BAB133D73106",
            "showAs": "purifier",
            "manualIP": "<removed>"
        }
    ],
    "platform": "Wemo"
}
```

![IMG_4917](https://user-images.githubusercontent.com/1724674/130884146-3c58bfbe-8a99-4b96-84c5-2579371618b5.jpg)
![IMG_4918](https://user-images.githubusercontent.com/1724674/130884148-1d6192e9-385c-495f-8b1d-b3afd6f915fb.PNG)

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?
v4.1.4

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wemo smart plug 2nd generation

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @vicc 

The "Wemo WiFi Smart Plug" accessory is nothing to do with Homebridge or the plugin. This looks like it could be the native homekit version of the device?

**Comment by vicc** [comment]
So in the previous archived project, if I changed an outlet type to `purifier`, it would simply update the existing outlet tile in HomeKit to that type.

The bug I'm seeing is that instead of updating the existing tile's type, it keeps the original and adds a new tile with `purifier`. 

Am I not supposed to add the smart plug to HomeKit directly and instead add it via homebridge only?

**Comment by bwp91** [comment]
If you add the device to homekit directly **and** add via homebridge, you will have two homekit accessories for the same device. Both will
show as a separate tile in home app and are completely independent.

This version of the plugin and the previous plugin homebridge-platform-wemo change the accessory type in exactly the same way, nothing has changed. If you change to a purifier, then it will remove the outlet tile and replace it with a purifier tile. So what you can see now is the homebridge purifier accessory, and the direct homekit outlet accessory.

If you were to change back from the purifier to default, you would see two outlet tiles, one from homebridge and the other the homekit-direct.

I hope this makes sense

**Comment by vicc** [comment]
Okay I figured it out. In order to prevent duplicate tiles, you need to reset your 2nd gen (home-kit) smart plug, and delete the Wemo app (this is necessary, so that when you reinstall it, you can block homekit permissions). Upon blocking homekit permissions, it will finally allow you to add your wemo plug directly to the wemo app without depending on homekit first. This then makes it discoverable to Homebridge, allowing it to create the purifier tile, without having to have the original outlet tile as well. Hope this helps future ppl.

**Comment by bwp91** [comment]
Glad you got this sorted.

Would it not have been easier to just remove the homekit native accessory directly from the home app?
