### ISSUE TITLE
Unupdateable switches

### ISSUE THREAD

**Issue by Movieaholic** [rudders/homebridge-wemo#34]
Hi Ive found a issue not with the plugin as such but i have a couple of wemo switches that i just opened recenly so the firmware is ancient before the move to cloud service for wemo, so i cant get them to connect to the wemo app or update the firmware for them, it sets up the switch and names it but it never shows up in the app so i tried manually adding it to this plugin and although it adds it its named "plugin light switch device" and the second one i added gets named the same thing so only one shows in homekit at once and when homebridge resets any changes that i make to it gets reverted back to what it was originally, im guessing this is because there is no cloud aspect to it, any chance there is something i could do so it doesnt reset it to a new device every time homebridge resets?

**Comment by bwp91** [comment]
Hi,
Can you update the plugin to v4.1.5? I'm hoping with the change I have made, the device serial number will be used for the accessory name. The plugin normally uses the device name from the wemo app... but obviously in your case this is not present.
The serial number for your two outlets will be different, so hopefully both will show in homebridge with the plugin being able to distinguish between them.
You *may* need to remove them from the homebridge cache as a one off after updating, so they are re-added using the serial number as the name.
Let me know if this works!

**Comment by Movieaholic** [comment]
Unfortunately they both have the serial number 123456789001 even though they have different serial numbers in the config

**Comment by Movieaholic** [comment]
Looking at what homebridge knows about them the only thing thats different between them is the ip address

**Comment by bwp91** [comment]
Can you visit the xml page of one of the devices (the View XML link in the plugin ui) and post on here the file contents?

**Comment by Movieaholic** [comment]
1 0 urn:Belkin:device:lightswitch:1 Plugin Light Switch Device Belkin International Inc. http://www.belkin.com Belkin Plugin Socket 1.0 LightSwitch 1.0 http://www.belkin.com/plugin/ 123456789001 uuid:Lightswitch-1_0-1234567890001 123456789 jpg 100 100 100 icon.jpg urn:Belkin:service:WiFiSetup:1 urn:Belkin:serviceId:WiFiSetup1 /upnp/control/WiFiSetup1 /upnp/event/WiFiSetup1 /setupservice.xml urn:Belkin:service:timesync:1 urn:Belkin:serviceId:timesync1 /upnp/control/timesync1 /upnp/event/timesync1 /timesyncservice.xml urn:Belkin:service:basicevent:1 urn:Belkin:serviceId:basicevent1 /upnp/control/basicevent1 /upnp/event/basicevent1 /eventservice.xml urn:Belkin:service:firmwareupdate:1 urn:Belkin:serviceId:firmwareupdate1 /upnp/control/firmwareupdate1 /upnp/event/firmwareupdate1 /firmwareupdate.xml urn:Belkin:service:rules:1 urn:Belkin:serviceId:rules1 /upnp/control/rules1 /upnp/event/rules1 /rulesservice.xml urn:Belkin:service:metainfo:1 urn:Belkin:serviceId:metainfo1 /upnp/control/metainfo1 /upnp/event/metainfo1 /metainfoservice.xml urn:Belkin:service:remoteaccess:1 urn:Belkin:serviceId:remoteaccess1 /upnp/control/remoteaccess1 /upnp/event/remoteaccess1 /remoteaccess.xml /pluginpres.html

**Comment by bwp91** [comment]
This really is a bit of an issue since the plugin is based around each device having a unique serial number and the individual accessory id is generated from the serial number.

Is there no way that you can update the firmware for the devices?

**Comment by Movieaholic** [comment]
No ive tried, once setup they don't show up in the app I have also tried a android emulator to install a older version of the app they show up before 1.25 but when trying to update firmware it says there's a problem try again later 1.25 says there is a update but when you accept and continue the app says upgrading but nothing happens even though these devices aren't on the list and anything after that they just aren't recognized

**Comment by Movieaholic** [comment]
Home assistant came to the rescue this time

**Comment by bwp91** [comment]
Ah, i’m glad you found a solution, I’m sorry i can’t be more helpful in this case.

It’s a strange one as you’d expect a unique serial number to be reported for every device and this is totally what the plugin is structured around.
