### ISSUE TITLE
[Eero] Connection Issues, Could not Find Port

### ISSUE THREAD

**Issue by kfinkbiner** [rudders/homebridge-wemo#37]
### What issue do you have? Please be as thorough and explicit as possible.
Homebridge Logs continually show error that there is a connection error, Could not find the correct port to the device.  This seems to cause lag when trying to use via the Home App

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v1.3.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Running on Linux Ubuntu Box. 
Node.js Version  v14.18.1
NPM v6.14.15

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?
homebridge-wemo v4.2.6

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
I have multiple light switches, dimmers and mini plugs.  

![Screenshot 2021-11-08 105451](https://user-images.githubusercontent.com/93940672/140793729-d0ee33e6-676d-4b62-a370-380c5a7c3ad7.png)

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @kfinkbiner 

Don’t suppose you have an eero router by any chance?

**Comment by kfinkbiner** [comment]
I am on an Eero system.

**Comment by bwp91** [comment]
At the same time of seeing these messages in the log? Is the device controllable via the wemo app? Or does it say undetected?

Please check next time you start to see these messages

**Comment by kfinkbiner** [comment]
So some devices are controllable but one device does say Undetected.  They are slow to respond in the Wemo app, but they do respond.

**Comment by kfinkbiner** [comment]
commenting so issue isn't closed.

**Comment by bwp91** [comment]
I’ve added a don’t close label so this issue doesn’t auto close. But I think the issue really is a connectivity issue between wemo devices and eero system. You’re the third person (including myself) who has noted this and it seems to have appeared since the eeroOS 3.5 update

**Comment by kfinkbiner** [comment]
Anything else I can do.  Escalate an issue to Eero?

**Comment by bwp91** [comment]
Sorry in my last comment I meant eeroOS 6.5 not 3.5.

Looks like eeroOS 6.6 has been released, and will be gradually rolled out over the next few days.

Once I've been able to update to it, it will interesting to see if anything has been fixed with regards to wemo devices and the connection.

**Comment by kfinkbiner** [comment]
Morning.  My eero updated to 6.6 last night.  Been monitoring it and I haven't seen those errors return.

**Comment by bwp91** [comment]
I have been monitoring myself since my network updates to 6.6, I haven't had any further issues or any connection errors in the homebridge log. I'm hoping the new version has resolved these connectivity issues... so far so good!

**Comment by skcuslleb** [comment]
I have the same issue with one of my devices, but I have a Synology router. The device is controllable from the Wemo app.

**Comment by kfinkbiner** [comment]
@bwp91 

So I am getting this error again on two different Wemo Plugs.  These are the newer Mini Plugs.  I added to my Wemo App via an Android Phone instead of adding straight into HomeKit.  Whenever I add them straight into HomeKit they always show "No Response"  I don't have that issue when running your plug-in.  I am sure this is on Wemo's end.

[12/1/2021, 9:20:04 PM] [Wemo] [192.168.4.47] connection error: could not find correct port for device.
[12/1/2021, 9:22:34 PM] [Wemo] [192.168.4.48] connection error: could not find correct port for device.

**Comment by bwp91** [comment]
Anyone who is using eero, can try updating to the beta version of the plugin and increasing the default upnp subscription time.

Via the UI, it's in the 'Advanced Settings' -> 'UPnP Subscription Interval'. Or the direct json entry is `"upnpInterval": 120`.

You can try increasing to for example 10 minutes (a value of `600`).

There will be no functionality change with the plugin except for how often the plugin renews the connection with the device. This increase _may_ improve the connectivity of these wemo devices on eero networks.

**Comment by kfinkbiner** [comment]
Just completed this.  I will monitor and report back.

**Comment by kfinkbiner** [comment]
Eero just updated to 6.6.1 and issue is back in full force.

**Comment by joeroks** [comment]
I have same issue with all my devices using Motorola gateway. All devices are good in the wemo app. Homebrige v1.3.8. Wemo Plugin v4.5.1 on raspberry pi.

Update: I have 5 wemo devices. 1 homekit compatible,  the other 4 are older devices and not compatible. The only device that connects with the plugin is the homekit-compatible one. All other devices get the following error:

[12/27/2021, 11:36:50 PM] [Wemo] [10.0.0.9] connection error: could not find correct port for device.
[12/27/2021, 11:39:42 PM] [Wemo] [10.0.0.23] connection error: could not find correct port for device.
[12/27/2021, 11:39:49 PM] [Wemo] [10.0.0.24] connection error: could not find correct port for device.
[12/27/2021, 11:39:49 PM] [Wemo] [10.0.0.21] connection error: could not find correct port for device.

**Comment by bwp91** [comment]
In the latest version of the plugin I have increased the time of the upnp subscription interval from 2 to 5 minutes. This also can be configured since a recent version of the plugin.

In the case of eero, the issue *may* have been that a upnp call every 2 minutes was picked up by the router as “spam” and so disconnected the device. I repeat this *may* be the case. And *maybe* similar for other routers?

Once you’ve been running the latest version of the plugin for a couple of days, could anyone let me know if they are still experiencing these connection issues?

**Comment by bwp91** [comment]
For some context, the plugin “subscribes” to a device for an X number of seconds to receive external updates. I can potentially set this to how ever long I like, but a longer interval means the plugin can’t detect an offline device so quickly.

This is what i mean by “upnp subscription interval” above.

**Comment by joeroks** [comment]
New update, v4.5.2, is working for me

**Comment by bwp91** [comment]
> New update, v4.5.2, is working for me

thanks, good to know 👍🏻

**Comment by kfinkbiner** [comment]
I am still getting Connection Port errors.  Running newest version.  UPnP is set to 600 as previously mentioned.  Devices still work just fine via Home App and such but logs are filled with this error.

**Comment by kfinkbiner** [comment]
Commenting so issue doesn’t close.

**Comment by kfinkbiner** [comment]
Connection errors seemed to have stopped as of yesterdays update.

**Comment by kfinkbiner** [comment]
Welp, I was wrong.  They are back.

**Comment by kfinkbiner** [comment]
Would it be beneficial if assign each of these devices static IPs?

**Comment by speedingcheetah** [comment]
I see this and similar in the logs. on all 6 Wemo plugs i have.

[1/28/2022, 7:33:32 PM] [Wemo] [192.168.0.67] connection error: could not find correct port for device.
[1/28/2022, 7:34:03 PM] [Wemo] [Heater] upnp error (will be re-attempted) [connect EHOSTUNREACH 192.168.0.67:49152].
[1/28/2022, 7:34:06 PM] [Wemo] [Heater] http error (will be re-attempted).

over and over again, but the plugs still work and respond fine.

I use Ubiquiti hardware. My router is a Ubiquiti EdgeRouter ER12, and wifi AP is a UniFi AC-LITE (only used for 2.4ghz network).
Plugs have DHCP Reservation set in router, so their IP stays the same.

I recently installed and setup this plugin on HB cause the plugs just connected via Native home kit became very unstable and not reliable with Siri being Cant reach wemo, not responding, took to long etc. Since moving them to HB and this plugin, so far, seems much more stable and responsive.

**Comment by bwp91** [comment]
> Would it be beneficial if assign each of these devices static IPs?

Could be worth a try. However the `could not find port` error is created when the plugin already has the IP of the device, either from the configuration or from the auto broadcasting to find devices on the network. If you try giving your devices static IPs then it would be worth manually configuring them in the wemo config too. Then you can also disable the broadcasting if you wish (may reduce some network traffic).

@speedingcheetah 

I added another config option in the last update to hide all these connection errors from the homebridge log. If you are happy that the plugin is still working as it should, then you could use this new option just to make your logs look cleaner without the errors.

**Comment by kvpoma** [comment]
Is there anyway someone can give instructions how to manually add the static ip to the config file?  I'm having the same issues with a Eero Pro 6 system.  Of course, it's only my old wemo light switches that have the constant could not find port error.  A screenshot of the config file with static ip's would help!

**Comment by bwp91** [comment]
I wonder if this comment here would help anyone still receiving these connection errors in the log?

https://github.com/bwp91/homebridge-wemo/issues/49#issuecomment-1055038772

**Comment by bwp91** [comment]
> Is there anyway someone can give instructions how to manually add the static ip to the config file? I'm having the same issues with a Eero Pro 6 system. Of course, it's only my old wemo light switches that have the constant could not find port error. A screenshot of the config file with static ip's would help!

Hi @kvpoma a config for 3 light switches would look like this:

```json
{
   "name": "Wemo",
   "wemoLights": [
      {
         "serialNumber": "22######",
         "label": "Light Switch Any Name 1",
         "manualIP": "192.168.1.1"
      },
      {
         "serialNumber": "22######",
         "label": "Light Switch Any Name 2",
         "manualIP": "192.168.1.2"
      },
      {
         "serialNumber": "22######",
         "label": "Light Switch Any Name 3",
         "manualIP": "192.168.1.3"
      }
   ],
   "platform": "Wemo"
}
```
