### ISSUE TITLE
Pull details from different subnet

### ISSUE THREAD

**Issue by turtle2472** [rudders/homebridge-wemo#38]
I have two Homebridge installs with one for my home and the second for an apartment that is on a different VLAN/subnet from the main house.  The plugin sees the Wemo devices on my network immediately but when I install the plugin on the apartment homebridge it doesn't since it is on a different subnet.  From the apartment VLAN I'm able to communicate with the items on the main network so there isn't a connectivity issue.

What I'm looking for is the ability to have the plugin poll the other network.

eg: Main 10.10.0.1/24, Apt 10.10.1.1/24
Apt HB Wemo plugin scan 10.10.0.1/24 for devices.

I know I'm a very small corner case, but it sure would be nice to be able to specify the network to scan for devices.

**Comment by bwp91** [comment]
Hi @turtle2472 

So do you have wemo devices on both subnets ie in your main house and in your apartment?

Any plugin instance should be able to discover and create the upnp connection on the same subnet as the plugin has an IP on. Your apartment homebridge should be able to find the devices on that subnet, is this working? Does the apartment homebridge instance have an IP on the same subnet as the apartment vlan?

**Comment by turtle2472** [comment]
The Wemo switches are on the main network with the main Homebridge.  The Apt VLAN is a different subnet from the main and it works well within that subnet.  However what I'm looking to do is be able to have the Apt Homebridge control "common" switches for exterior lights on the property.  The physical switches are in the main dwelling so they are  connected to the main homebridge.  

What I need is to be able to tell the plugin in the apt homebridge to look for devices on the main (10.10.0.1/24) subnet.  This way those switches will be discovered on the Apt network.

**Comment by bwp91** [comment]
The wemo devices advertise themselves on the local network using [SSDP](https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol).

The plugin uses [NodeSSDP](https://github.com/diversario/node-ssdp) to look for the wemo devices on the local network. You can use the plugin config to configure the available options for NodeSSDP, in particular the options

```json
"wemoClient": {
  "discover_opts": {
    "interfaces": "",
    "explicitSocketBind": true
  }
}
```

These two options will be passed to the NodeSSDP client. Unfortunately there doesn't appear to be an option to specify a subnet range, only the network interface to search on (which by default is all interfaces). Your apartment homebridge instance will need to also have an IP from the main house subnet for the devices to automatically be discovered.

My recommendation would be to give the wemo devices static IPs if you haven't already, and use the plugin configuration on the apartment homebridge instance to manually define the devices with their IPs. I would also disable UPnP as this is unlikely to work. When UPnP is disabled, the plugin will use local HTTP polling to keep the status of each device up to date. This should work properly as you have already said

> From the apartment VLAN I'm able to communicate with the items on the main network so there isn't a connectivity issue.

**Comment by turtle2472** [comment]
The plugin works great if I manually configure the IPs of the switches, my reason for the request here is so we can see about adding additional subnets to the plugin going forward.  Plus, the "Manual Devices (Deprecated)" section leaves me to believe at some point it will disappear.  So asking for something permanent is really the goal while allowing more complex environments.

**Comment by bwp91** [comment]
will mark this as don’t close…

**Comment by bwp91** [comment]
> Plus, the "Manual Devices (Deprecated)" section leaves me to believe at some point it will disappear.

The manual devices section will at some point be removed, but, the same functionality is possible in the device type specific sections, ie, with a label, serial number and an IP

**Comment by bwp91** [comment]
I don’t think this feature request is going to be possible.

The plugin (using nodeSSDP) can only broadcast a request for upnp devices on any subnet that the homebridge instance is physically on.

If the homebridge instance is on 192.168.1.X **and** 192.168.2.X then it can discover devices on both. However if the instance isn’t on 192.168.2.X (albeit it may have access via …1.X) it can’t discover the devices.
