### ISSUE TITLE
No devices shown after reboot

### ISSUE THREAD

**Issue by Schattenkaiser** [rudders/homebridge-wemo#39]
### What issue do you have? Please be as thorough and explicit as possible.
I Wasn't able to access to my devices. After several tries (including reboot the service, and the hoobs as well) I decided to use the clear cache function.
Now after restarting the whole thing, I can't see any of my devices, and wemo isn't discovering the devices even with mode=auto

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Hoobs

* Which version of Homebridge/HOOBS do you have?
4.1.17

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
RPi 4  on Node 16.13.1 and HB-Version 1.3.6

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?
4.3.0
I'm not sure abaout the time when this issue shows up for the first time

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
all of my devices are affected:
2 Outlets
5 Lightbulbs

### Please paste any relevant logs below.

```
7.12.2021, 16:51:31Wemo BridgeConfiguration change
7.12.2021, 16:51:31wemobridge stopping
7.12.2021, 16:51:32Wemo BridgeWemoSSDP client gracefully stopped.
7.12.2021, 16:51:32Wemo BridgeWemoListener server gracefully closed.
7.12.2021, 16:51:37Wemo Bridge starting
7.12.2021, 16:51:40Wemo BridgeLoaded plugin 'homebridge-wemo'
7.12.2021, 16:51:40Wemo BridgeLoading 1 platforms...
7.12.2021, 16:51:40Wemo BridgeWemoInitialising plugin v4.3.0 | Node v16.13.1 | HB v1.3.6 | HOOBS v4...
7.12.2021, 16:51:40Wemo BridgeWemoPlugin initialised. Setting up accessories....
7.12.2021, 16:51:40Wemo BridgeWemodiscovering all IPs from interface lo
7.12.2021, 16:51:40Wemo BridgeWemodiscovering all IPs from interface wlan0
7.12.2021, 16:51:40Wemo BridgeWemoWill use interface wlan0
7.12.2021, 16:51:40Wemo BridgeWemoListener server port [44927].
7.12.2021, 16:51:40Wemo BridgeWemoSSDP listening: { address: 'http://192.168.0.158:46745', interface: '192.168.0.158' }
7.12.2021, 16:51:40Wemo BridgeWemoAttempting to send an M-SEARCH request
7.12.2021, 16:51:40Wemo BridgeWemoSending a message to 239.255.255.250:1900
7.12.2021, 16:51:40Wemo BridgeBridge is running on port 51836.
7.12.2021, 16:51:40Wemo BridgeWemoSent M-SEARCH request: {
  message: 'M-SEARCH * HTTP/1.1\r\n' +
    'HOST: 239.255.255.250:1900\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'MAN: "ssdp:discover"\r\n' +
    'MX: 3\r\n' +
    '\r\n',
  id: '64057c5a597d19e7'
}
7.12.2021, 16:51:42Wemo BridgeWemo✓ Setup complete. Want to see this plugin in your own language? Let me know!
7.12.2021, 16:52:10Wemo BridgeWemoAttempting to send an M-SEARCH request
7.12.2021, 16:52:10Wemo BridgeWemoSending a message to 239.255.255.250:1900
7.12.2021, 16:52:10Wemo BridgeWemoSent M-SEARCH request: {
  message: 'M-SEARCH * HTTP/1.1\r\n' +
    'HOST: 239.255.255.250:1900\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'MAN: "ssdp:discover"\r\n' +
    'MX: 3\r\n' +
    '\r\n',
  id: 'ca5acd0ad39ca291'
}
```

**Comment by bwp91** [comment]
Hi @Schattenkaiser 

Are the devices on the same subnet as your HOOBS instance ie all your devices have an IP address 192.168.0.X?

**Comment by Schattenkaiser** [comment]
yes - all devices are setup in the same (Mesh) WLAN with 192.168.0.X

**Comment by bwp91** [comment]
and do you have upnp enabled on your router?

**Comment by Schattenkaiser** [comment]
I've done the upgrade to 4.4.0 a few minutes ago, and this is, what the protocol says:

''
8.12.2021, 17:52:25wemobridge stopping
8.12.2021, 17:52:25Wemo BridgeWemoStopped socket on 192.168.0.158
8.12.2021, 17:52:25Wemo BridgeWemoSSDP client gracefully stopped.
8.12.2021, 17:52:25Wemo BridgeWemoWARNUNG[Gartenlicht Garage Wemo] existing upnp subscriptions have been stopped.
8.12.2021, 17:52:25Wemo BridgeWemoListener server gracefully closed.
8.12.2021, 17:52:25Wemo BridgeWemo[Gartenlicht Garage Wemo] [urn:Belkin:service:basicevent:1] unsubscribe successful.
8.12.2021, 17:52:30Wemo Bridge starting
8.12.2021, 17:52:33Wemo BridgeFEHLER[31mThe plugin "homebridge-wemo" requires a Homebridge version of ^1.3.8 which does not satisfy the current Homebridge version of 1.3.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
8.12.2021, 17:52:34Wemo BridgeLoaded plugin 'homebridge-wemo'
8.12.2021, 17:52:34Wemo BridgeLoading 1 platforms...
8.12.2021, 17:52:34Wemo BridgeWemoInitialising plugin v4.4.0 | Node v16.13.1 | HB v1.3.6 | HOOBS v4...
8.12.2021, 17:52:34Wemo BridgeWemoPlugin initialised. Setting up accessories....
8.12.2021, 17:52:34Wemo BridgeWemodiscovering all IPs from interface lo
8.12.2021, 17:52:34Wemo BridgeWemodiscovering all IPs from interface wlan0
8.12.2021, 17:52:34Wemo BridgeWemoWill use interface wlan0
8.12.2021, 17:52:34Wemo BridgeWemoListener server port [39749].
8.12.2021, 17:52:34Wemo BridgeWemoSSDP listening: { address: 'http://192.168.0.158:46786', interface: '192.168.0.158' }
8.12.2021, 17:52:34Wemo BridgeWemoAttempting to send an M-SEARCH request
8.12.2021, 17:52:34Wemo BridgeWemoSending a message to 239.255.255.250:1900
8.12.2021, 17:52:34Wemo BridgeBridge is running on port 51836.
8.12.2021, 17:52:34Wemo BridgeWemoSent M-SEARCH request: {
  message: 'M-SEARCH * HTTP/1.1\r\n' +
    'HOST: 239.255.255.250:1900\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'MAN: "ssdp:discover"\r\n' +
    'MX: 3\r\n' +
    '\r\n',
  id: '57658f1d32e84f05'
}
8.12.2021, 17:52:34Wemo BridgeWemoSSDP response: {
  message: 'HTTP/1.1 200 OK\r\n' +
    'CACHE-CONTROL: max-age=86400\r\n' +
    'DATE: Wed, 08 Dec 2021 16:55:06 GMT\r\n' +
    'EXT:\r\n' +
    'LOCATION: http://192.168.0.105:49153/setup.xml\r\n' +
    'OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01\r\n' +
    '01-NLS: 90019290-bfde-11d3-9965-ac0eabfd7f3e\r\n' +
    'SERVER: Unspecified, UPnP/1.0, Unspecified\r\n' +
    'X-User-Agent: redsonic\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'USN: uuid:Socket-1_0-221304K11000AD::urn:Belkin:service:basicevent:1\r\n' +
    '\r\n'
}
8.12.2021, 17:52:34Wemo BridgeWemoSSDP response: {
  message: 'HTTP/1.1 200 OK\r\n' +
    'CACHE-CONTROL: max-age=86400\r\n' +
    'DATE: Wed, 08 Dec 2021 16:55:06 GMT\r\n' +
    'EXT:\r\n' +
    'LOCATION: http://192.168.0.105:49153/setup.xml\r\n' +
    'OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01\r\n' +
    '01-NLS: 90019290-bfde-11d3-9965-ac0eabfd7f3e\r\n' +
    'SERVER: Unspecified, UPnP/1.0, Unspecified\r\n' +
    'X-User-Agent: redsonic\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'USN: uuid:Socket-1_0-221304K11000AD::urn:Belkin:service:basicevent:1\r\n' +
    '\r\n'
}
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] initialising with options {"logging":"debug","showAs":"outlet"}.
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] initialised with s/n 221304K11000AD and ip/port 192.168.0.105:49153
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] http has been established.
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] [urn:Belkin:service:basicevent:1] initial subscription for service.
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] upnp has been established.
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] receiving update [BinaryState: 1].
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] current state [on].
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>1</BinaryState>
</e:property>
</e:propertyset>
8.12.2021, 17:52:34Wemo BridgeWemo[Gartenlicht Garage Wemo] receiving update [BinaryState: 1].
8.12.2021, 17:52:36Wemo BridgeWemo✓ Setup complete. Have time to give this plugin a review? http://bit.ly/hbwemo-review
8.12.2021, 17:53:04Wemo BridgeWemoAttempting to send an M-SEARCH request
8.12.2021, 17:53:04Wemo BridgeWemoSending a message to 239.255.255.250:1900
8.12.2021, 17:53:04Wemo BridgeWemoSent M-SEARCH request: {
  message: 'M-SEARCH * HTTP/1.1\r\n' +
    'HOST: 239.255.255.250:1900\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'MAN: "ssdp:discover"\r\n' +
    'MX: 3\r\n' +
    '\r\n',
  id: 'ff9194a5e805a60b'
}
8.12.2021, 17:53:04Wemo BridgeWemoSSDP response: {
  message: 'HTTP/1.1 200 OK\r\n' +
    'CACHE-CONTROL: max-age=86400\r\n' +
    'DATE: Wed, 08 Dec 2021 16:55:36 GMT\r\n' +
    'EXT:\r\n' +
    'LOCATION: http://192.168.0.105:49153/setup.xml\r\n' +
    'OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01\r\n' +
    '01-NLS: 90019290-bfde-11d3-9965-ac0eabfd7f3e\r\n' +
    'SERVER: Unspecified, UPnP/1.0, Unspecified\r\n' +
    'X-User-Agent: redsonic\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'USN: uuid:Socket-1_0-221304K11000AD::urn:Belkin:service:basicevent:1\r\n' +
    '\r\n'
}
8.12.2021, 17:53:04Wemo BridgeWemoSSDP response: {
  message: 'HTTP/1.1 200 OK\r\n' +
    'CACHE-CONTROL: max-age=86400\r\n' +
    'DATE: Wed, 08 Dec 2021 16:55:36 GMT\r\n' +
    'EXT:\r\n' +
    'LOCATION: http://192.168.0.105:49153/setup.xml\r\n' +
    'OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01\r\n' +
    '01-NLS: 90019290-bfde-11d3-9965-ac0eabfd7f3e\r\n' +
    'SERVER: Unspecified, UPnP/1.0, Unspecified\r\n' +
    'X-User-Agent: redsonic\r\n' +
    'ST: urn:Belkin:service:basicevent:1\r\n' +
    'USN: uuid:Socket-1_0-221304K11000AD::urn:Belkin:service:basicevent:1\r\n' +
    '\r\n'
}

''

so it seems wemo has found one of my outlets (called Gartenlicht), and I'm able to switch it on and of with my Hoobs

**Comment by bwp91** [comment]
Ah, promising.

Can you power cycle the other outlet to see if the plugin picks it up? And the lightbulbs... I assume you have a wemo link? can you power cycle this too?

Are you on eero network?

**Comment by Schattenkaiser** [comment]
>
> Are you on eero network?

what does that mean. I'm not sure I understand

**Comment by Schattenkaiser** [comment]
btw the second outlet came back - only the lightbulbs are missing

**Comment by Schattenkaiser** [comment]
the system protocol now says:
8.12.2021, 18:06:31Wemo BridgeFEHLER[31mThe plugin "homebridge-wemo" requires a Homebridge version of ^1.3.8 which does not satisfy the current Homebridge version of 1.3.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m

So can you tell me, howto upgrade the HB Version? I'm not really familiar with Linux code

**Comment by bwp91** [comment]
> > Are you on eero network?
> 
> what does that mean. I'm not sure I understand

Do you have eero router?
https://eero.com

With regards to the message about the homebridge version, you can ignore this until hoobs release an update with homebridge 1.3.8.

Which version of hoobs are you currently running?

**Comment by Schattenkaiser** [comment]
![image](https://user-images.githubusercontent.com/80150829/145265043-399e5875-9d2c-46d4-a099-4bcad0a7de97.png)

.. and no, no eero - I'm using the netgear orbi system

**Comment by bwp91** [comment]
This is fine. I think HOOBS 4.1.18 will be released soon which will include homebridge 1.3.8. Until then, this will have no effect on the plugin.

For your wemo lightbulbs, do you use a wemo link as the bridge?

**Comment by Schattenkaiser** [comment]
> 
> For your wemo lightbulbs, do you use a wemo link as the bridge?

yes - there is Wemo Link used as a bridge. I've unpowered the link and put into a outlet again, but the lightbulbs are still missing

**Comment by bwp91** [comment]
Can you give the wemo link fixed ip from your router settings, and then configure the device manually in the plugin settings?

**Comment by Schattenkaiser** [comment]
is this the right place to set the IP?
![image](https://user-images.githubusercontent.com/80150829/145386724-fdc5064b-6899-4c7c-995d-48f5ce155cfa.png)

**Comment by Schattenkaiser** [comment]
I'm getting this messages now:

''
9.12.2021, 12:17:17wemobridge stopping
9.12.2021, 12:17:17Wemo BridgeWemoSSDP client gracefully stopped.
9.12.2021, 12:17:17Wemo BridgeWemoListener server gracefully closed.
9.12.2021, 12:17:22Wemo Bridge starting
9.12.2021, 12:17:25Wemo BridgeFEHLER[31mThe plugin "homebridge-wemo" requires a Homebridge version of ^1.3.8 which does not satisfy the current Homebridge version of 1.3.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
9.12.2021, 12:17:26Wemo BridgeLoaded plugin 'homebridge-wemo'
9.12.2021, 12:17:26Wemo BridgeLoading 1 platforms...
9.12.2021, 12:17:26Wemo BridgeWemoInitialising plugin v4.4.0 | Node v16.13.1 | HB v1.3.6 | HOOBS v4...
9.12.2021, 12:17:26Wemo BridgeWemoPlugin initialised. Setting up accessories....
9.12.2021, 12:17:26Wemo BridgeWemoListener server port [42131].
9.12.2021, 12:17:26Wemo BridgeBridge is running on port 51836.
9.12.2021, 12:17:26Wemo BridgeWemoWARNUNGSSDP search failed as NodeSSDP error [no sockets], if this continues to happen try restarting Homebridge.
9.12.2021, 12:17:28Wemo BridgeWemo✓ Setup complete. Want to see this plugin in your own language? Let me know!
''

**Comment by bwp91** [comment]
No, remove the IP from the discovery interfaces option, then find the "Wemo Links" config item and press the "+".

Should look like this:

<img width="685" alt="Screenshot 2021-12-09 at 11 19 58" src="https://user-images.githubusercontent.com/43026681/145387376-205d08f1-0ff3-462e-a7c5-150d1fadfbac.png">

Enter a label (just so you know which device this refers to) enter the serial number of the wemo link and finally the IP just as `192.168.0.173`.

**Comment by Schattenkaiser** [comment]
like this?

''
{
    "platform": "Wemo",
    "name": "Wemo",
    "mode": "auto",
    "debug": true,
    "debugFakegato": false,
    "debugNodeSSDP": false,
    "wemoLinks": [
        {
            "manualIP": "192.168.0.173:49153/setup.xml"
        }
    ]
}
''

**Comment by Schattenkaiser** [comment]
![image](https://user-images.githubusercontent.com/80150829/145389759-b74a9fbb-3dac-45f2-b8fa-56923337539c.png)

**Comment by bwp91** [comment]
Would need to be like this:

```json
{
  "platform": "Wemo",
  "name": "Wemo",
  "mode": "auto",
  "debug": true,
  "debugFakegato": false,
  "debugNodeSSDP": false,
  "wemoLinks": [
    {
      "label": "Wemo Link",
      "serialNumber": "SERIAL NUMBER",
      "manualIP": "192.168.0.173"
    }
  ]
}
```

**Comment by bwp91** [comment]
Obviously replacing `SERIAL NUMBER` with the serial number of the wemo link device

**Comment by Schattenkaiser** [comment]
done - but without any positive result.
![image](https://user-images.githubusercontent.com/80150829/145392910-d3c9fcc0-8268-4ff3-bfd7-7676e69111be.png)

btw. when I'm lookin at the protocoll, I can't see the second outlet (Blumensäule) either. But this outlet could be seen in Bridge Cache
![image](https://user-images.githubusercontent.com/80150829/145392405-c5bb0d20-05fa-4992-ad6b-9f4f8bcc75ac.png)

... and also in the accessories
![image](https://user-images.githubusercontent.com/80150829/145392592-97a2086f-73e3-4472-bd25-97db8b9d931d.png)
but when I try to switch the Blumensäule on/off it does nothing. The highlighted button disappears (like off status), but the light is still on.
It looks like my hoobs has no longer the control about my accessories but I can only control the lights and switches with the original APPs

**Comment by bwp91** [comment]
Are you able to disable the 5ghz band on your router, at least temporarily, to see if this makes a difference with the plugin?

So disable the 5ghz so the network is totally 2.4ghz band, unpower your wemo devices and plug them back in, once they are back online then restart the plugin to see if they are discovered?

If this doesn't work, then at least this is ruled out as to why the plugin can't find/control them

**Comment by Schattenkaiser** [comment]
I've checked this before. All affected accessories are connected with the 2.4 ghz connection, so I understand this should not be the issue.
The only difference is, that the Raspberry Pi is connected with 5 ghz to the router.

I didn't change this configuration since years, and therefore I don't believe that this could cause the problem, as it worked before over years in the same setup.

**Comment by bwp91** [comment]
Is there a way you can force your raspberry pi to use the 2.4ghz band to see if this makes a difference?

**Comment by Schattenkaiser** [comment]
It made no difference to run on 2.4ghz only, so I set everything back as it was before.

After todays most recent hoobs update to 4.1.18 and HB Version 1.3.8 and the restart of my Network-System, everything is working as expected now.
WEMO-Plugin found all of the accessories again, and enables me to modify all automations in iOS Homekit-APP and as well on my hoobs.

Thanks you for your patience - this task is resolved.
