### ISSUE TITLE
High CPU on macOS

### ISSUE THREAD

**Issue by jasonsnell** [rudders/homebridge-wemo#40]
### What issue do you have? Please be as thorough and explicit as possible.

With homebridge-wemo installed, process `homebridge` runs at 100% CPU.

With it disabled, process `homebridge` idles at < 1% CPU.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1.

* Which version of Homebridge/HOOBS do you have?

HomeBridge 1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

macOS Mojave - Mac mini server. Node 16.13.1, Npm 8.1.2.

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?

I previously used homebridge-wemo-platform. Now on 4.4.0 of homebridge-wemo.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

**Comment by bwp91** [comment]
Hi @jasonsnell 

Im afraid I don't experience this on my macbook pro.

Do you have a lot of wemo devices on your network?

**Comment by jasonsnell** [comment]
I only have a couple?

Config file is set to auto. I turned on Debug but don't see anything. I have absolutely confirmed that the CPU usage only happens when homebridge-wemo is enabled.

```
      {
            "name": "Wemo",
            "mode": "auto",
            "debug": true,
            "platform": "Wemo"
        }
```

**Comment by bwp91** [comment]
Can you (as a test), configure both your devices in the config with manual IPs, and set the mode to manual, (this will disable the discovery) to see if this makes any difference?

**Comment by jasonsnell** [comment]
Yes, after switching to manual and manually adding the one device I own that doesn't already support HomeKit, that absolutely solved the issue. It's running with control over that device at 0.5% CPU.

**Comment by bwp91** [comment]
Seems like the network broadcasting/discovery was making the CPU run at 100%. I haven't seen this issue before.

The plugin uses [NodeSSDP](https://github.com/diversario/node-ssdp) to handle this functionality, I've even looked through the issues on that repo, but nothing seems to have been reported.

Is your network a kinda standard setup? Or do you have multiple vlans/subets? Does your mac use multiple network interfaces?

**Comment by jasonsnell** [comment]
Pretty standard. Server is on Ethernet. Has Wi-Fi but isn't on that network. One subnet on the network, everything's on it.
