### ISSUE TITLE
Can’t Dim Wemo bulbs

### ISSUE THREAD

**Issue by jacklawry** [rudders/homebridge-wemo#43]
### What issue do you have? Please be as thorough and explicit as possible.
Was working fine but recent update seems to have stopes ability to dim bulbs (still works in wemo app) and can turn them on and off. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X 

* Which version of Homebridge/HOOBS do you have?
V1.3.9

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
RPi
Node 16.13.1 

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?
V4.5.3

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

Wemo bulbs

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @jacklawry 

Just to clarify, are you talking about the wemo bulbs connected via a wemo link?

Is this since an update to the plugin or a firmware update to the link / bulbs?

**Comment by jacklawry** [comment]
@bwp91 Yes it is the wemo bulbs with a link. From further testing it seems to only be an issue with one of the three bulbs I have. 

It seems to have happened since updating the homebridge plugin, or perhaps a coincidence... and odd that others work so perhaps not related.

**Comment by bwp91** [comment]
Are there any errors in the homebridge log when you try to change the brightness for this particular bulb?

If you use the wemo app to change the brightness for this bulb, does it update in home app?

**Comment by jacklawry** [comment]
Just checked the 3rd one and that's not working either. 

No logs at all when two of the bulbs change only via wemo or HB just for the one that works. 

Changing in the wemo app is only updating the single one that works and updating via HB only updates the working one in wemo. 

Oddly the one that works is furthest away from the bridge. 

Going to power cycle the bridge and all 3 bulbs to see if that helps.

**Comment by jacklawry** [comment]
Unfortunately restarting bulbs and Wemo Link didn't make any difference.

**Comment by jacklawry** [comment]
Oddly this seems to have fixed itself... Not sure if it was an issue with the bulbs, the link or Homebridge? 

Happy to close.

**Comment by bwp91** [comment]
Hiya, sorry didnt get back to you, but glad to hear it's fixed, how strange.

I'll close, hopefully you won't have issues again in the future!
