### ISSUE TITLE
Wemo CoffeeMaker Implementation

### ISSUE THREAD

**Issue by neuor1** [rudders/homebridge-wemo#45]
Hello,

Thank you for your work on this plugin! I have a Wemo CoffeeMaker among other Wemo devices. I understand it is not supported by this plugin. However, my Homebridge log is filled with "[Wemo] [CoffeeMaker] [urn:Belkin:device:CoffeeMaker:1] is unsupported but feel free to create a GitHub issue." Is it possible to disable this from being logged?

**Comment by bwp91** [comment]
Hey, would you be interested in helping me implement this device somehow into homekit?

**Comment by bwp91** [comment]
You can also update to the beta version of the plugin. This should stop the repeated log entries for this device.

https://github.com/bwp91/homebridge-wemo/wiki/Beta-Version

Thanks!

**Comment by neuor1** [comment]
Sure, how can I help? I know the Home Assistant Wemo integration supports the coffee maker. Not sure if it would help as a reference. https://github.com/home-assistant/core/tree/dev/homeassistant/components/wemo

**Comment by bwp91** [comment]
Are you able to show me a screenshot of how the coffee machine looks in the wemo app? To see which features are available to control?

**Comment by neuor1** [comment]
Screenshots attached. As you can see the CoffeeMaker reports back to the app when the water tank is empty. When full, the coffee cup icon becomes the brew button. The Wemo app also offers a brew schedule and water filter reminder.

**Comment by neuor1** [comment]
Looks like the screenshots didn’t make it with my email reply. 
![F8B405EC-8990-48D8-AEBF-950B3D4249BA](https://user-images.githubusercontent.com/89746117/150536405-1de81942-6261-4d58-982e-71e76185883e.jpeg)
![7C8AECCF-F63C-4EEA-9CCB-22A2786B57B7](https://user-images.githubusercontent.com/89746117/150536446-fd7c2056-05a8-414b-9730-5037a68fbbb9.jpeg)

**Comment by bwp91** [comment]
To be honest I’m quite unsure of which homekit accessory type and what features I can expose to HomeKit, any ideas? 😊

**Comment by neuor1** [comment]
So the Home Assistant integration simply supported controlling the brew cycle as a switch. Toggle the brew cycle on, the HomeKit switch would stay on until the brew cycle completed and then the HomeKit switch would turn off.  Turning the HomeKit switch off mid brew would cancel the brew cycle. That’s all that is really needed. Once in HomeKit as a switch it can be added to an automation or scene.

**Comment by bwp91** [comment]
Could you update the plugin to beta version 4.5.5-beta.3, the accessory should appear as a switch.

I've had to do a bit of guess work with the values for the modes, but I'm hoping it properly reflects whether the machine is brewing, and also if you control the homekit switch it should change the machine to brewing mode (or not).

Let me know whether it's working or any errors you encounter! Thanks

**Comment by neuor1** [comment]
The coffee maker was discovered and added to homekit as a switch. Toggling
the switch triggered the brew cycle. The switch turned off when the brew
cycle completed. The one thing I did test that didn't work is I turned the
switch off after starting the brew cycle and it did not stop the brew
cycle. Thank you for your work on this! We're almost there!

**Comment by bwp91** [comment]
Are you able to turn the brew cycle off via the wemo app if it has started?

**Comment by neuor1** [comment]
The Wemo app does not support canceling the brew process. In fact, once brewing the brew button turns into a brewing icon and is no longer a button. 

Having the ability to trigger the brew cycle from HomeKit is perfect. In an ideal world it would be nice to get the status information from the coffee maker in HomeKit. However, without native HomeKit support that doesn’t seem possible.

Thank you again for your work on this!

**Comment by bwp91** [comment]
I noticed here 
https://github.com/openhab/openhab-addons/blob/6df6783b60e1651399585c575da7ed1a18783454/bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java#L190
that turning off isn’t supported.

In the new beta, i have changed the plugin to show a no response in the home app if you try to turn it off. and then revert back to on. are you able to test this?

**Comment by neuor1** [comment]
It functioned as you described and displayed an error icon on the HomeKit button when I attempted to turn it off.

**Comment by bwp91** [comment]
Just released v4.6.0 with support for the coffee maker! Will close this issue now.
