### ISSUE TITLE
Info: Plugin does not recognize node.js version

### ISSUE THREAD

**Issue by RuntyCascade** [rudders/homebridge-wemo#48]
I am running Node.js version v16.13.1

Homebridge-wemo plugin shows this in logs:
`The plugin "homebridge-wemo" requires Node.js version of ^14.18.3 || ^16.13.2 which does not satisfy the current Node.js version of v16.13.1. You may need to upgrade your installation of Node.js`

Not sure if this would cause issues at some point.

**Comment by bwp91** [comment]
Hi @RuntyCascade 

The plugin will always recommend the latest versions of node for 

* Maintenance LTS currently v14
* Active LTS v16

This does not mean that earlier versions of node won't work.

In your case with using node v16.13.1 the plugin will work absolutely fine, you can ignore the warning, but I always recommend keeping your node version up to date at least if you were to update to v16.14.0.

hope this helps
