### ISSUE TITLE
3-way switch issues

### ISSUE THREAD

**Issue by gadgetvirtuoso** [rudders/homebridge-wemo#53]
### What issue do you have? Please be as thorough and explicit as possible.

When using Siri to turn on the light that is a 3-way Wemo switch the switch will toggle twice in very short succession, causing the light not to turn on/off. You can hear it switch toggle twice when this occurs and sometimes the switch will show as being on/off in Homebridge even though the light is not on/off. You then need to toggle the light on/off again to get it back in sync with what Homebridge and HomeKit think the light status is. Sometimes this needs to be done multiple times.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
 Homebridge UI

* Which version of Homebridge/HOOBS do you have?
Homebridge 1.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Synology APK
Node.js v16.13.2
NPM v6.14.15

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?

homebridge-wemo v4.7.2

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

WeMo_WW_2.00.11563.PVT-OWRT-LIGHTV2
Lightswitch v3

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @gadgetvirtuoso 

Sorry taken a while to get back to you.

Is this still an issue? I assume it is since I haven't changed the plugin.

Are you able to turn on plugin debug logging and get some logs when you turn on this device from homebridge?
