### ISSUE TITLE
Reinstall of everything Plugin not finding devices and being stopped by Homebridge

### ISSUE THREAD

**Issue by timmeade** [rudders/homebridge-wemo#55]
### What issue do you have? Please be as thorough and explicit as possible.

I just reinstalled everything including node js on a mac mini.

so far all other plugins working great.  

Wemo plugin not finding any devices.  All on same subnet.  Prior installation it did work. 

Last lines in logs are:
[4/11/2022, 9:24:44 AM] [Homebridge UI] [homebridge-wemo] Terminating child process...
[4/11/2022, 9:24:44 AM] [Homebridge UI] [homebridge-wemo] Child process ended

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebrige

* Which version of Homebridge/HOOBS do you have?

homebridege v1.4.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

macos Mojave
Node v16.14.0

* Which version of this plugin (homebridge-wemo) do you have? Has the issue started since upgrading from a previous version?
homebridge-wemo v4.7.2
I tried homebridge-wemo v4.7.1 and same issues

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

All Wemo devices Light switchs and smart plugs

### Please paste any relevant logs below.

```
[4/11/2022, 9:24:10 AM] [Wemo] Listener server port [49358].
[4/11/2022, 9:24:12 AM] [Wemo] ✓ Setup complete. Want to see this plugin in your own language? Let me know!
[4/11/2022, 9:24:44 AM] [Homebridge UI] [homebridge-wemo] Terminating child process...
[4/11/2022, 9:24:44 AM] [Homebridge UI] [homebridge-wemo] Child process ended

```

**Comment by bwp91** [comment]
Hi @timmeade 

Are you still having issues with this?

**Comment by theking81** [comment]
Yes this is also the problem with me. After reinstall, i cannot locate any plugs, even with manual installation.

**Comment by jmaugerdumais** [comment]
Hello!
I have precisely the same issue. 

Tried with macOS and Ubuntu as host system.

Also note that the plug-in doesn't detect the switch. 

Thanks !

**Comment by davidjaystrauss** [comment]
Hi All,

I just tried installing this plugin and am having the same issue.

I believe my problem might be tied to the fact that my Homebridge host machine is on my 5ghz network band, while my WeMo switches are on my 2.4ghz band, could that have anything to do with this?

It's difficult to move my host over to the 2.4 band or I would try it out, but that's my best guess right now at least.

Thanks for any info

**Comment by theking81** [comment]
> Hi All,
> 
> I just tried installing this plugin and am having the same issue.
> 
> I believe my problem might be tied to the fact that my Homebridge host machine is on my 5ghz network band, while my WeMo switches are on my 2.4ghz band, could that have anything to do with this?
> 
> It's difficult to move my host over to the 2.4 band or I would try it out, but that's my best guess right now at least.
> 
> Thanks for any info

I am having the same issue... all my wemo my devices are on 2.4ghz band same IP's 192.168.x.x with my homebridge (its on local lan with eth cable)  but my devices are nowhere to be found, even with custom entering the devices. I have no idea why is this happening. I have tried everything. Even setting up everything from the beginning.

**Comment by theking81** [comment]
Had the same issue. Fixed the problem. The fix was easy. I added a new wi/fi network 2.4ghz with access to the local network (same ip range and default gateway). And all devices are online :)
