### ISSUE TITLE
Wemo Devices work in Homebridge but show as "No Response" in Home App

### ISSUE THREAD

**Issue by joeroks** [rudders/homebridge-wemo#59]
I don't believe this is a plugin issue but here is my problem. I am running the latest homebridge and wemo plugin version on a raspberry pi. Everything looks good in homebridge. I can turn on/off my 3 devices. When I add the devices to the home app, they seem ok for a few minutes and then I get the dreaded "No Response" on all devices. I've tried resetting all the devices, the raspberry pi, and my iPhone 12. I've removed the devices from the app then re-added them and I get the same behavior. I don't know what else to do. Also, the devices work correctly in the wemo app. The 3 wemo devices are all homekit compatible but since I don't have a homekit hub (ipad, apple tv), I am using the homebridge app as my hub.

**Comment by bwp91** [comment]
Hi @joeroks, just out of interest when you say

> I am using the homebridge app as my hub.

what do you mean by this?

**Comment by joeroks** [comment]
Ben,  I was mistaken. Homebridge is not a hub. I either need an Apple tv,  HomePod mini or iPad. I don’t need homebridge if my Wemo’s  are HomeKit compatible. Sorry for the confusion. 


Joe Roks
