### ISSUE TITLE
Error running homebridge-wemo

### ISSUE THREAD

**Issue by Dave10950** [rudders/homebridge-wemo#6]
Hi, I'm really new to all of node.js and npm, yesterday I had an issue with another homebridge plugin (but this worked fine) so I updated my node and npm versions and now i'm having trouble with this plugin, the error code is attached below, please help. Thank you

any help is greatly appreciated! thank you.

[Homebridge-wemo errors.pdf](https://github.com/rudders/homebridge-wemo/files/93662/Homebridge-wemo.errors.pdf)

**Comment by IMNotMax** [comment]
Hi, what is your platform ?

**Comment by IMNotMax** [comment]
Moreover, you can go to [homebridge-platform-wemo](https://github.com/rudders/homebridge-platform-wemo) to have a full automated wemo platform.
@rudders made an amazing job with the platform.
try a `sudo npm install -g homebridge-platform-wemo`and follow some instructions to configure the config.json file.

**Comment by Dave10950** [comment]
I'm so sorry for bothering, turns out I had uninstalled the wemo plugin and forgot about it, I reinstalled it and everything works fine now...

**Comment by jtepp** [comment]
Sorry I know this is urelted but how DO you uninstall a plugin?

**Comment by rudders** [comment]
`sudo npm rm -g <plugin name>`
