### ISSUE TITLE
Plugin crashes Homebridge

### ISSUE THREAD

**Issue by SteliosMakrinos** [rudders/homebridge-wemo#7]
Occasionally (every few hours or every couple of days) the wemo plugin crashes Homebridge with the following output:

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at WeMoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/index.js:77:7)
    at /usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:110:5
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:99:4)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:240:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

**Comment by rudders** [comment]
Please move to https://github.com/rudders/homebridge-platform-wemo - it is far more stable and functional.

**Comment by SteliosMakrinos** [comment]
I had done this...but then switched back because of the "force" crashing of homebridge.  I will try again.

**Comment by rudders** [comment]
The force crash is very useful to ensure your homekit configuration is never damaged by the plugin if it can't find all your accessories when restarting - make sure you have specified the exact number of accessories you have in config.json.

**Comment by SteliosMakrinos** [comment]
I switched to the platform just now.  Specified the correct number of devices, reset my homekit configuration, but now 1 of the devices appears twice.  Reset the config again and re-added homebridge, but have the same problem.

**Comment by SteliosMakrinos** [comment]
Nevermind...my mistake, left one of the WeMo accessories in the config.son.
