### ISSUE TITLE
Wemo maker in switch mode = no response

### ISSUE THREAD

**Issue by dvd2000k** [rudders/homebridge-wemo#70]
Hi, if i configure a Wemo Maker as a switch, once i restart Homebridge (1.5.0 with node 16.16.0) in home app i have “ no response “ warning. If i open the Homebridge UI, i can control the Wemo maker and the “no response” message in home app disappear. 

The plugin is the latest (5.0.3).

**Comment by bwp91** [comment]
Hi @dvd2000k 
Thanks for reporting this.
If you update to the beta version of the plugin do you still experience this?

**Comment by theking81** [comment]
Had the same issue, removed the plugin and installed it again, and then... i cant add any devices.

**Comment by theking81** [comment]
Had the same issue. Fixed the problem. The fix was easy. I added a new wi/fi network 2.4ghz with access to the local network (same ip range and default gateway). And all devices are online :)
