### ISSUE TITLE
Node version not satisfied?

### ISSUE THREAD

**Issue by scaryfast8750** [rudders/homebridge-wemo#83]
Seeing this in Homebridge logs:

The plugin "homebridge-wemo" requires Node.js version of ^14.20.1 || ^16.18.0 || ^18.11.0 which does not satisfy the current Node.js version of v19.2.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

[Wemo] Initialising plugin v5.0.5 | System darwin | Node v19.2.0 | HB v1.6.0 | HAPNodeJS v0.11.0...

**Environment details:**
Node Version:  19.2

**results of update command:**
sudo hb-service update-node 
ℹ Node.js v19.2.0 already up-to-date.

npm -v
9.1.3

homebridge 1.6.0
homebridge-wemo v5.0.5
homebridge-config-ui-x v4.50.2

**Comment by bwp91** [comment]
Hi @scaryfast8750 

This is simply because homebridge itself does not officially support odd numbered versions of node.

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

If you don’t experience any issues with the plugin then you can simply ignore this message!

**Comment by scaryfast8750** [comment]
Got it.  Thank you!
